


# VAD
SILENCE_DURATION_FOR_VALIDATION=1000
SAMPLE_RATE = 16000
BLOCK_SIZE = 512  # ~30 ms

# WHISPER CONFIG

LANGUAGE = "fr"
WHISPER_MODEL_SIZE="small"  # tiny, base, small, medium, large
DEVICE="cpu"
COMPUTE_TYPE="int8"